// <auto-generated />
using System;
using Barford_Inventory_System.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barford_Inventory_System.Migrations
{
    [DbContext(typeof(BISDbContext))]
    [Migration("20240806162325_AddOrdersEntity")]
    partial class AddOrdersEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Barford_Inventory_System.DTOs.ItemDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Barford_Inventory_System.DTOs.OrderDTO", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OutDate")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Barford_Inventory_System.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderDTOGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.HasIndex("OrderDTOGroupId");

                    b.HasIndex("OrderGroupId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Barford_Inventory_System.Models.Order", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Barford_Inventory_System.Models.Item", b =>
                {
                    b.HasOne("Barford_Inventory_System.DTOs.OrderDTO", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderDTOGroupId");

                    b.HasOne("Barford_Inventory_System.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderGroupId");
                });

            modelBuilder.Entity("Barford_Inventory_System.DTOs.OrderDTO", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Barford_Inventory_System.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
